In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import os
import folium
import json

In [3]:
# This command propts matplotlib visuals to appear in the notebook 
%matplotlib inline

In [5]:
# Import ".json" file for the U.S. 
country_geo = r'/Users/samarjitgehdu/Documents/Achievement 6/Gun Violence/us-states.json'

In [7]:
# Create a path
path = r'/Users/samarjitgehdu/Documents/Achievement 6/Gun Violence'

In [9]:
path

'/Users/samarjitgehdu/Documents/Achievement 6/Gun Violence'

In [11]:
# Importing the gun violence file
df = pd.read_csv(os.path.join(path,'02 Data', 'Prepared Data', 'Gun_Violence_Clean_Data(2013-2018).csv'))

In [13]:
# Wrangle the Data. Extract state-wise incident count
df['state'] = df['state'].astype(str)
state_incidents = df['state'].value_counts().reset_index()
state_incidents.columns = ['state', 'incident_count']

In [15]:
# Clean the Data/Check for missing values
missing_values = df.isnull().sum()

In [17]:
missing_values

Unnamed: 0                     0
incident_id                    0
date                           0
state                          0
city_or_county                 0
address                        0
n_killed                       0
n_injured                      0
incident_url                   0
source_url                     0
incident_url_fields_missing    0
congressional_district         0
gun_stolen                     0
gun_type                       0
incident_characteristics       0
latitude                       0
longitude                      0
n_guns_involved                0
notes                          0
participant_age_group          0
participant_gender             0
participant_status             0
participant_type               0
sources                        0
state_house_district           0
state_senate_district          0
dtype: int64

In [19]:
df.head()

,Unnamed: 0,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,...,longitude,n_guns_involved,notes,participant_age_group,participant_gender,participant_status,participant_type,sources,state_house_district,state_senate_district
0,0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,...,-79.8559,1.0,Julian Sims under investigation: Four Shot and...,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://pittsburgh.cbslocal.com/2013/01/01/4-pe...,-1.0,-1.0
1,1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,http://www.gunviolencearchive.org/incident/460726,http://www.dailybulletin.com/article/zz/201301...,...,-118.3330,1.0,Four Shot; One Killed; Unidentified shooter in...,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://losangeles.cbslocal.com/2013/01/01/man-...,62.0,35.0
2,2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,http://www.gunviolencearchive.org/incident/478855,http://chronicle.northcoastnow.com/2013/02/14/...,...,-82.1377,2.0,Unknown,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,http://www.morningjournal.com/general-news/201...,56.0,13.0
3,3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,http://www.gunviolencearchive.org/incident/478925,http://www.dailydemocrat.com/20130106/aurora-s...,...,-104.8020,1.0,Unknown,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://denver.cbslocal.com/2013/01/06/officer-...,40.0,28.0
4,4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,http://www.gunviolencearchive.org/incident/478959,http://www.journalnow.com/news/local/article_d...,...,-79.9569,2.0,Two firearms recovered. (Attempted) murder sui...,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://myfox8.com/2013/01/08/update-mother-sho...,62.0,27.0

In [21]:
# Display basic descriptive stats
summary_stats = df.describe(include='all')

In [23]:
summary_stats

,Unnamed: 0,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,...,longitude,n_guns_involved,notes,participant_age_group,participant_gender,participant_status,participant_type,sources,state_house_district,state_senate_district
count,239677.000000,2.396770e+05,239677,239677,239677,239677,239677.000000,239677.000000,239677,239677,...,239677.000000,239677.000000,239677,239677,239677,239677,239677,239677,239677.000000,239677.000000
unique,NaN,NaN,1725,51,12898,198038,NaN,NaN,239677,213990,...,NaN,NaN,136653,899,874,2151,260,217281,NaN,NaN
top,NaN,NaN,2017-01-01,Illinois,Chicago,Unknown,NaN,NaN,http://www.gunviolencearchive.org/incident/461105,http://blog.tsa.gov,...,NaN,NaN,Unknown,0::Adult 18+,0::Male,0::Injured,0::Victim,http://blog.tsa.gov,NaN,NaN
freq,NaN,NaN,342,17556,10814,16497,NaN,NaN,1,1092,...,NaN,NaN,81017,94671,93496,42293,58564,1092,NaN,NaN
mean,119838.000000,5.593343e+05,NaN,NaN,NaN,NaN,0.252290,0.494007,NaN,NaN,...,-89.236244,1.217902,NaN,NaN,NaN,NaN,NaN,NaN,46.315808,17.579618
std,69188.934572,2.931287e+05,NaN,NaN,NaN,NaN,0.521779,0.729952,NaN,NaN,...,14.131003,3.583024,NaN,NaN,NaN,NaN,NaN,NaN,43.750294,15.112348
min,0.000000,9.211400e+04,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,...,-171.429000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,-1.000000
25%,59919.000000,3.085450e+05,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,...,-93.600900,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,9.000000,5.000000
50%,119838.000000,5.435870e+05,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,...,-86.249600,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,35.000000,15.000000
75%,179757.000000,8.172280e+05,NaN,NaN,NaN,NaN,0.000000,1.000000,NaN,NaN,...,-80.136700,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,77.000000,29.000000
max,239676.000000,1.083472e+06,NaN,NaN,NaN,NaN,50.000000,53.000000,NaN,NaN,...,97.433100,400.000000,NaN,NaN,NaN,NaN,NaN,NaN,901.000000,94.000000

In [25]:
# 5. Create a Choropleth Map
# Center the map around the continental US
map_center = [37.8, -96]
choropleth_map = folium.Map(location=map_center, zoom_start=4)

folium.Choropleth(
    geo_data = country_geo,
    name = 'choropleth map',
    data = state_incidents,
    columns = ['state', 'incident_count'],
    key_on = 'feature.properties.name',
    fill_color = 'YlGnBu',
    fill_opacity = 0.7,
    line_opacity = 0.2,
    legend_name = 'Gun Violence Incidents per State (2013–2018)'
).add_to(choropleth_map)

folium.LayerControl().add_to(choropleth_map)

In [27]:
# Save map as HTML in project folder
choropleth_map.save(os.path.join(path, '04 Analysis','Visualizations', "gun_violence_choropleth_map.html"))


#### Analysis Summary
##### This choropleth map displays the total number of gun violence incidents across each US state between 2013 and 2018. 
###### The darker blue tones indicate higher counts of reported incidents.

#### Key Insights:
##### - States such as California, Texas, and Florida show significantly higher incident counts.
##### - Northeastern and rural states have lower incident frequencies.
##### - Geographic clustering indicates possible socioeconomic or policy-driven trends.

#### Research Questions Answered:
##### - **Which states exhibit the highest and lowest rates of gun violence?**

#### New Research Questions Raised:
##### - Are high-incident states correlated with urban population density?
##### - How do state-specific policies impact gun violence trends?